# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAy6hXi-MODfwH2Tm5yqWLtAiKpZuhVP
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def printinfo(self):
    print(self.name)
    print(self.age)

samuraitarou = Human("侍大郎", 36)

samuraitarou.printinfo()