# -*- coding: utf-8 -*-
"""kadai_005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSDuBaVxmKpG4ORK08GD1q7mjjvMLoz9
"""

top_side = 10
bottom_side = 20
height = 5
trapezoid = str((top_side + bottom_side) * height /2) + "cm2"
print(trapezoid)