# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHLI7dvGghYhmMerl308PQP3tiFoNYpX
"""

def tax_included(price, tax):
  total = price + price * tax / 100
  print(total)

tax_included(100, 10)