# -*- coding: utf-8 -*-
"""kadai_011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQpVD-_8hs6JciKloAjqkNN1qU8Pxd5C
"""

array = ["水", "金", "地", "火", "木", "土", "天", "海", "冥"]

for i in array:
  print(i)

i = 0
while i < 9:
  print(array[i])
  i = i + 1